### ISSUE TITLE
SAP_Toolkit: Copy & clean Bluebeam markup xml

### ISSUE THREAD

**Issue by rboulton-BH** [BHoM/SAP_Toolkit#25]
#### Description:

Bluebeam markups are an intrinsic part of the SAP 2D workflow and the intention is to use [XML_Toolkit to bring in Bluebeam markups as BHoM objects](https://github.com/BHoM/XML_Toolkit/tree/main/XML_oM/Bluebeam).

However, the XML output from Bluebeam is not quite valid for MS parsing so bit of pre-processing is required. Specifically, if a markup does not have a value for a given property then it will only provide the closing tag of the property instead of both the opening and closing tags e.g. `</Label>` instead of `<Label></Label>`. 

Example file and use case can be found in [this closed issue on XML_TK](https://github.com/BHoM/XML_Toolkit/issues/539)

We need to develop a standalone method to:
1. Read XML data from a user input filepath
2. Find and fix instances of incorrect syntax e.g. where no opening label is provided
3. Save a copy of the 'cleaned' xml file in the same location as the original (i suggest appending "_cleaned" or similar to the filename)
4. Similar to Push/Pull/Execute methods, I think it would be good to have an 'active' boolean user input to enable control of when the file is read and copied.

**Comment by rboulton-BH** [comment]
To complicate this issue a bit further here are some observations:

SAP XML schema also uses the `<Description/>` notation for an empty property suggesting that this is actually valid XML syntax. It also means we will need to be able to handle this notation (in a better way than just find/replace) for future SAP XML interoperability.

Bluebeam XML schema appears to include whitespace after the property name when the property value is empty. For example:  `<Space />` rather than what I would expect `<Space/>`. Could this be causing issues with the MS serializer?

@emilsvedjer - could you please investigate these cases a bit further to better understand what is the root cause of the issue and therefore how to resolve it?

**Comment by emilsvedjer** [comment]
I tested this and it generates the same error as with the <enum />,  for now I would say that find/replace is the best way to go since it's the only thing that works...
